export const DUPLICATE_COMMAND = 'duplicate command names'
export const DUPLICATE_OPTION = 'duplicate option names'
export const EXISTING_SUBCOMMAND = 'cannot set existing command as subcommand'
export const EXPECT_COMMAND_NAME = 'expect a command name'
export const INVALID_CHARACTER = 'invalid characters'
export const WRONG_CONTEXT = 'invalid context path'
export const WRONG_SUBCOMMAND = 'invalid subcommand'
